name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
      env:
        CI: true
    - run: mkdir vendor vendor-zip && cp -r *.js ./data ./node_modules vendor/
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./vendor-zip/433Remote-dist.zip ./vendor
    - name: deploy
      uses: appleboy/lambda-action@master
      with:
        args: --function-name 433Remote --zip-file ./vendor-zip/433Remote-dist.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1
